config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'
  get 'favorites/destroy'
  get 'posts/show'
  get 'posts/index'
  get 'comments/create'
  get 'comments/destroy'
  get '/signup', to: 'users#new'

  root to: 'posts#index'
  # get 'pages/top'
  get '/signup', to: 'users#new'  # => このルーティング要る？

  get '/login', to: 'sessions#new'  #=> コンフリクト?。
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users    # usersテーブルに登録したユーザーのページ
  resources :posts

  # 画像とコメント、お気に入りを紐づけるルーティング
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  validates :title, presence: true, length: { maximum: 50 }
  validates :image, presence: true
  default_scope -> { order(created_at: :desc ) }
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #引数で渡されたユーザidがFavoritesテーブル内に存在するかどうかを調べるメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    # favorites.exists?(user_id: user.id)
  end
  
  validates :title, presence: true
  validates :image, presence: true  
  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord                                    
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy   

    before_save { self.email = email.downcase }  #アドレスの大文字小文字は区別しない。そのため、保存の前に、小文字に変換してから保存。
    validates :name, presence: true, length: { maximum: 50 }

    validates :email, presence: true, length: { maximum: 255 },
                        uniqueness: { case_sensitive: false } # case_sensitive => 大文字、小文字を区別する。falseで区別しない。
    
    has_secure_password             # デフォルトで、パスワードのバリデーション機能が付いている。テストも起動する。？（ 新規登録時にのみ適用される。　）
                                    # passwordと、password_confirmationが使えるようになる。
                                    # dbのカラムに、password_digestを追加すると使用できるようになる。
    validates :password, presence: true, length: { minimum: 6 }
    
                            # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    include SessionsHelper  # => どのコントローラーからでも、sessions_helperが呼び出せるようになる

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.all
    comment = current_user.comments.new(comment_params)
    comment.user_id = current_user.id
    comment.save
    redirect_to request.referer  #同じページをリダイレクト
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'コメント削除に失敗しました'
      render post_path(@post)
    end
  end

  private
    def comment_params
        params.require(:comment).permit(:comment, :post_id)  #formにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    # redirect_to post_path(post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    # redirect_to post_path(post)
  end

  private
  
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :correct_user, only: :destroy
  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    if @post.save
      flash[:sucess] = "投稿しました！"
      redirect_to current_user
    else
      render 'show'
    end
  end


  def show
    # @user = User.find(params[:id])
    # @post = @user.posts
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    @post.destroy
    flash[:sucess] = "投稿を削除しました！！"
    redirect_to request.referer || root_url
  end

  def index
    @posts = Post.all
    @posts = @posts.page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  private

    def post_params
      params.require(:post).permit(:title, :image)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to user_url if @post.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "ログインしました！"
      redirect_to user
    else
      flash.now[:danger] = "メールアドレスと、パスワードが正しくありません"
      render 'new'
    end
    
  end

  def destroy
    # reset_session
    log_out
    flash[:sucsess] = "ログアウトしました"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user # => @userが、createアクションの初めで、定義されている。
      flash[:success] = "アカウント登録成功しました。#{@user.name}さん、ようこそ！！"
      redirect_to @user
    else
      flash.now[:failed] = "アカウント登録に失敗しました"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @post = current_user.posts.build
    # @posts = current_user.posts.page(params[:page]).per(1)
    @posts = @user.posts.page(params[:page]).per(10)
  end
end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user) # => 引数のuser（変数）を渡して、ログイン
        session[:user_id] = user.id  # => cookieに保存されているuserのデータを、一時的（ブラウザが閉じるまで）にsessionメソッドに保存できる。
    end
    

    def current_user # => 現在ログイン中のユーザーを返す（いる場合）
        if session[:user_id]
            @current_user ||= User.find_by( id: session[:user_id] ) 
        end
    end

    def logged_in?  # 評価を論理値で返すメソッド　=> userがログインしていたら、true!それ以外はfalseを返す。
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post), method: :DELETE, remote: true, class: "favorite_btn" do %>
        ♥<%= post.favorites.count %>like
    <% end %>

    <% else %>
    <%= link_to post_favorites_path(post), method: :POST, remote: true, class: "favorite_btn" do %>
        ♡<%= post.favorites.count %>like
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-brand">
            <%= link_to "ホーム", posts_path, class: "nav-link" %>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: "nav-link" %></li>
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to "マイページ", current_user, class: "nav-link" %></li>
                    <li class="nav-item nav-link"><%= "#{current_user.name}でログイン中"%></li>
                    <li class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %></li> 
                <% else %>
                    <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>   
                <% end %>
            </ul>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |key, value| %>
        <div><%= value %></div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post_form.html.erb
<h1>記事の作成</h1>
<%= form_with(model: @post, local: true) do |f| %>
    <div class="form-group mt-3">
        <%= f.label :タイトル %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= f.label :写真 %>
        <%= f.file_field :image%>
    </div>
    <div class="mt-3">
        <%= f.submit "投稿", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/posts/index.html.erb
<h3 class="mt-3">投稿一覧</h3>

<div class="post-containe">
    <%= paginate @posts %>
    <% @posts.each do |post| %>
        <div class="border p-3 mx-auto mt-3" style="width: 30%;">
            <div>
                <%= post.user.name %>
            </div>
            <div class="post-title">
                <%= link_to post.title, post %>
            </div>
            <div class="post-image">
                <%= link_to (image_tag post.image.url), post %>
            </div>
            <div>投稿日: <<%= post.created_at.to_date %>></div>
            
            <% if logged_in? %>  <%# => ログインしているuserじゃないと、favoriteが表示できないエラーになる!! %>
                <div id="favorite_btn_<%= post.id %>">
                    <%= render 'favorites/favorite', post: post %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

<%# js使えてるかのテスト
「テスト」ではなく「成功」と表示されてればjs動いてる

<p>テスト</p>
<script type="text/javascript">
    $(document).ready(function() {
        $("p").text("成功！！");
    });
</script> %>
    <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>記事の作成</h1>
<%= form_with(model: @post, local: true) do |f| %>
    <div>
        <%= f.label :タイトル %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :写真 %>
        <%= f.file_field :image%>
    </div>
    <div>
        <%= f.submit "投稿" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<h3 class="mt-3">画像詳細ページ</h3>
<div class="w-50 mx-auto">
    <p class="h3">
        <span>画像タイトル：</span><%= @post.title %>
    </p>
    <p>
        <%= image_tag @post.image.url, class: "w-100" %>
    </p>
</div>

<div class="modal-content w-50 mx-auto" style="margin-top: 60px;">
    <div class="modal-body">
        <%= form_with(model:[@post, @comment], method: :post) do |f| %>
            <%= f.text_area :comment, placeholder: "コメント…", class: "form-control", rows: "5"  %>        
            <%= f.hidden_field :post_id, :value => @post.id %>
            <%# <%= f.hidden_field :user_id, :value => current_user.id%>
            <div class="mx-auto text-end mt-3">
                <%= f.submit "コメントする", class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

<h3 class="mt-5">コメント一覧</h3>
<table class="border w-100 mb-5">
    <div class="comment-index">
        <% @post.comments.each do |comment| %>
            <tr class="h4">
                <td><%= comment.user.name %></td>
                <td><%= comment.comment %></td>
                <td><%= button_to '削除する', post_comment_path(@post, comment), data: {confirm: "削除してよろしいですか？"}, method: :delete %></td>
            </tr>
        <% end %>
    </div>
</table>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div><%= @user.errors.count %>個のエラー</div>
    <div>
        <% @user.errors.full_messages.each do |message| %>
            <ul>
                <li><%= message %></li>
            </ul>
        <% end %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1 class="mt-3">ユーザー登録</h1>
<div class="border mt-5 p-5">
    <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'error_messages' %>
        <div class="form-group mb-3">
            <%= f.label :名前 %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= f.label :メールアドレス %>
            <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= f.label :パスワード %>
            <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
            <%= f.label :パスワード（確認用）%>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
            <%= f.submit "登録", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<h3 class="mt-3">マイページ</h3>

<div class='mypage row p-5'>
    <div class="side col-7">
        <h1 class='side_profile'>
            <div><%= @user.name%></div>
            <div><%= @user.email%></div>
        </h1>
        <div class='side_form mt-5 border w-50 p-2'>
            <%= render 'posts/post_form'%>
        </div>
    </div>
    <div class='posts col-5 border p-3'>
        <h2>投稿</h2>
        <% if @user.posts.any? %>
            <p>
                <%= @user.posts.count %>件の投稿
            </p>
            <%= paginate @posts %>
            <% @posts.each do |post|%>
                <ul class="list-group w-100 mt-5">
                    <h3 class="post_title"><%= link_to post.title, post %></h3>
                    <li class="list-group-item"><%= link_to image_tag(post.image_url, class: "w-100"), post %></li>
                    <li class="list-group-item">投稿日: <<%= post.created_at.to_date %>></li>
                    <li class="list-group-item">
                        <%# if current_user.post? %>
                            <%= link_to "削除", post, method: :delete, data: { confirm: "本当に消しますか？"}%>
                        <%# end %>
                    </li>
                </ul>
            <% end %>
            <%= paginate @posts %>
        <% end %>
    </div>
</div>